package player;

import java.util.Random;
/** 
 * A singleton class containing static methods that emulate a box of dice. 
 *  
 * It uses a static instance of java.util.Random, and as such may not be  
 * thread-safe on pre-Java5 virtual machines. 
 */ 
public class d10
{
    
    final private static Random random  = new Random(); 
    /** 
     * Roll a single die of the specified size. 
     *  
     * @param sides 
     *            the size of the die to roll, ie the number of sides 
     * @return a random value between 1 and the value of sides, inclusive. 
     */ 
    final public static int d( int sides ) 
    { 
        // Input validation 
        if( sides <= 0 ) 
            sides = 1; 
        // Generate and return a result 
        return random.nextInt( sides ) + 1; 
    } 
    /** 
     * Roll a number of dice of the specified size and return the total. 
     *  
     * @param num 
     *            the number of dice to roll. 
     * @param sides 
     *            the size of the dice to roll, ie the number of sides 
     * @return the total of the values generated by rolling the specified number 
     *         of dice of the specified size. 
     */ 
    final public static int d( int num, int sides ) 
    { 
            // Input validation 
            if( num <= 0 ) 
                num = 1; 
            if( sides <= 0 ) 
                sides = 1; 
            // Generate and return a result 
            int total = 0; 
            for( ; num > 0; num-- ) 
                total += random.nextInt(sides) + 1; 
            return total; 
    } 
    /** 
     * Roll a number of dice of the specified size and apply the given modifier. 
     * If the result is less than 1, then 1 is returned. 
     *  
     * @param num 
     *            the number of dice to roll. 
     * @param sides 
     *            the size of the dice to roll, ie the number of sides 
     * @param bonus 
     *            the bonus/penalty to apply to the total of the roll. 
     * @return the total of the values generated by rolling the specified number 
     *         of dice of the specified size, plus the bonus, but not less than 
     *         1. 
     */ 
    final public static int d( int num, int sides, int bonus ) 
    { 
            // Input validation 
            if( num <= 0 ) 
                num = 1; 
            if( sides <= 0 ) 
                sides = 1; 
            // Generate a result 
            int total = d( num, sides ) + bonus; 
            // Output validation 
            if( total < 1 ) 
                total = 1; 
            // Return the result 
            return total; 
    } 
}   
    



